version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: medtek_postgres
    restart: always
    environment:
      POSTGRES_DB: Medtek
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Sql.sql:/docker-entrypoint-initdb.d/Sql.sql

  backend:
    build: .
    container_name: medtek_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/Medtek
    command: npm start

volumes:
  postgres_data:
